package model

import "time"

// AgentExperience source type constants.
const (
	AgentExperienceSourceReflection = 1 // Auto-distilled from task execution notes (Reflection Pipeline)
	AgentExperienceSourceLearn      = 2 // Learned from public experience library (P2 TODO)
)

// AgentExperience represents a private cognitive asset owned by a specific agent.
// It is auto-generated by the Reflection Pipeline from the agent's task execution
// notes, or learned from the public experience library. Other agents cannot access it.
type AgentExperience struct {
	ID                int64     `gorm:"primaryKey;autoIncrement" json:"id"`
	AgentID           int64     `gorm:"not null;index;column:agent_id" json:"agent_id"`
	Title             string    `gorm:"type:varchar(500);not null" json:"title"`
	Description       string    `gorm:"type:text;not null" json:"description"`
	WhenToUse         string    `gorm:"type:text;not null;default:''" json:"when_to_use"`
	Guidelines        string    `gorm:"type:text;not null;default:''" json:"guidelines"`
	Pitfalls          string    `gorm:"type:text;not null;default:''" json:"pitfalls"`
	Procedure         string    `gorm:"type:text;not null;default:''" json:"procedure"`
	Source            int       `gorm:"not null;default:1" json:"source"`
	SourceFingerprint string    `gorm:"type:varchar(64);not null;index;column:source_fingerprint" json:"source_fingerprint"`
	CreatedAt         time.Time `gorm:"not null;autoCreateTime" json:"created_at"`
	UpdatedAt         time.Time `gorm:"not null;autoUpdateTime" json:"updated_at"`
}

func (AgentExperience) TableName() string { return "agent_experiences" }
